### ISSUE TITLE
Cytokine correlation matrix

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/tfac-mrsa#170]
One for serum, another for plasma.

**Comment by JacksonLChin** [comment]
Just to make sure I have the concept right---the idea is to evaluate correlation between each pair of cytokines, correct? And that'll we'll want to develop two--one for each source?

**Comment by aarmey** [comment]
Yep! The plot you already made let's us see if there are overall differences in cytokine amount. This lets us look for differences in cytokine-cytokine relationships.
