### ISSUE TITLE
Need a cartoon like the one in the systems serology paper

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/tfac-mrsa#43]
Can get you a copy of Affinity Designer if helpful. You could probably copy some things from the systems serology file.

**Comment by scottdtaylor95** [comment]
Would you be able to send me Affinity Designer? Also, do I need to look into a tutorial or is it fairly straightforward?

**Comment by aarmey** [comment]
There's a free trial to start here: https://affinity.serif.com/en-us/designer/

I think it's fairly straightforward, but I'm probably a terrible judge for this. I think they do have good resources on the "LEARN" tab.

**Comment by scottdtaylor95** [comment]
Added in recent "Fixing issues" PR
