### ISSUE TITLE
We will need a clinical correlates table

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/tfac-mrsa#44]
Like this one in Rossetti et al. You might want to email David G to help with this as I'm sure he's made many of these.

<img width="334" alt="Screen Shot 2021-02-22 at 3 34 47 PM" src="https://user-images.githubusercontent.com/2065146/108784115-81fbcc80-7523-11eb-9424-d9b59afeb6e4.png">

"Gjertson, David" <dgjertson@mednet.ucla.edu>

**Comment by scottdtaylor95** [comment]
What output should the table be in? I could probably make something in excel pretty easily, but that doesn't seem like an ideal format.

**Comment by aarmey** [comment]
Excel would be great, as we could easily convert it to other things from there.

**Comment by scottdtaylor95** [comment]
Do you know how to calculate the p value? It seems like a Fisher test, but I'm not quite sure how to do that for 1 by 1 tables

**Comment by aarmey** [comment]
You really, really should just email Prof. G and work with him on this. He's a professor of biostatistics, and funded on the grant. This could very well take 2 minutes of his time.

**Comment by scottdtaylor95** [comment]
Okay, will do.

**Comment by scottdtaylor95** [comment]
I asked Dr. Gjertson and he let me know which methods to use, so I should be set for that. However, I don't have any metadata for cohort 3. Is that okay?

**Comment by scottdtaylor95** [comment]
Also, should I create a table for all categories/variables here: https://www.pnas.org/content/pnas/116/40/20087.full.pdf or a subset?

**Comment by aarmey** [comment]
I believe he should have metadata on cohort 3.

He can probably make a table of everything like here.

**Comment by scottdtaylor95** [comment]
Oh, should I have asked him to make the table? I only asked for the methods/tests to use on the data.

**Comment by aarmey** [comment]
When he gets back to you, you might ask whether it's easier for him to put it together, given I think he makes these all the time.

**Comment by scottdtaylor95** [comment]
I asked him about cohort 3. He said that since we are blinded, we don't have clinical data for any of it. He did say that he could make the table, but said he needed the patient IDs and factors we are using for our analysis. I'm not quite sure what he means by the second part. What would you like me to do here?

**Comment by aarmey** [comment]
Ok, let's wait until we know whether some of cohort 3 will be unblinded.

**Comment by aarmey** [comment]
Being handled by Duke.
