### ISSUE TITLE
Make performance plots of the individual data types

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/tfac-mrsa#45]
While we're waiting on the factorization model, we could still finalize the ROC plots for using each individual data type:

- Cytokines with LR
- Gene expression with LR

I know you included SVM of cytokines in here previously, but I like being consistent with the Rossetti et al manuscript in using a linear model.

**Comment by scottdtaylor95** [comment]
Okay. I believe Jackson is including these as part of his analysis, using the raw data types compared with the factored patient by component. Should I instead do this part and/or should he remove them from his analysis? If I do, should I use all features, or some combination?

**Comment by aarmey** [comment]
Hmm... we can wait on this and decide later.
