### ISSUE TITLE
Two plots of cytokine data

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/tfac-mrsa#46]
- Plot of correlation between serum and plasma for each cytokine. In other words, the x-axis indicates the cytokine, the y-axis is a Pearson correlation.
- Plot of each cytokine amount separated by outcome and serum/plasma. Probably some [kind of point plot](https://seaborn.pydata.org/generated/seaborn.pointplot.html#seaborn.pointplot).

**Comment by scottdtaylor95** [comment]
Should I plot the raw values, or normalized?

**Comment by aarmey** [comment]
Probably want to use normalized, or they'll be on wildly different scales.

**Comment by scottdtaylor95** [comment]
Also, for the second plot all data that we currently have outcomes for only has 1 source or the other. Should I do separate plots for serum and plasma, or still do them together?

**Comment by aarmey** [comment]
Good point. We can have separate outcome- and type-separated plots.

**Comment by scottdtaylor95** [comment]
Just added in recent PR. We will still need to choose which cytokines to display in the main figure.
